UPDATE LocalizedText SET Text = Text||' Grants one free [ICON_GreatWork_Relic] Relic.'
WHERE Tag IN ('LOC_BUILDING_MONT_ST_MICHEL_DESCRIPTION', 'LOC_BUILDING_ST_BASILS_CATHEDRAL_DESCRIPTION', 'LOC_BUILDING_AL_STPETERSBASILICA_DESCRIPTION')
AND Language = 'en_US';

UPDATE LocalizedText SET Text = Text||'赠送一件免费的 [ICON_GreatWork_Relic] 遗物。'
WHERE Tag IN ('LOC_BUILDING_MONT_ST_MICHEL_DESCRIPTION', 'LOC_BUILDING_ST_BASILS_CATHEDRAL_DESCRIPTION', 'LOC_BUILDING_AL_STPETERSBASILICA_DESCRIPTION')
AND Language = 'zh_Hans';

UPDATE LocalizedText SET Text = Text||'授予一件免費的 [ICON_GreatWork_Relic] 遺物。'
WHERE Tag IN ('LOC_BUILDING_MONT_ST_MICHEL_DESCRIPTION', 'LOC_BUILDING_ST_BASILS_CATHEDRAL_DESCRIPTION', 'LOC_BUILDING_AL_STPETERSBASILICA_DESCRIPTION')
AND Language = 'zh_Hant';